### ISSUE TITLE
dep-graph gives weird error with empty robot path

### ISSUE THREAD

**Issue by JensTimmerman** [hpcugent/easybuild-framework#1188]
```
easyconfigs (develop) $ eb --dep-graph=bla.txt f/FSL/FSL-5.0.8-intel-2015a.eb --debug
Couldn't import dot_parser, loading of dot files will not be possible.
== temporary log file in case of crash /var/folders/jm/n5601wf51s17tnrq597z541c0000gn/T/easybuild-8Fk9YX/easybuild-rmfWpb.log
Traceback (most recent call last):
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/easybuild_framework-2.0.0dev-py2.7.egg/easybuild/main.py", line 335, in <module>
    main()
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/easybuild_framework-2.0.0dev-py2.7.egg/easybuild/main.py", line 290, in main
    dep_graph(options.dep_graph, ordered_ecs)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/easybuild_framework-2.0.0dev-py2.7.egg/easybuild/framework/easyconfig/tools.py", line 180, in dep_graph
    _dep_graph(*args, **kwargs)
  File "/Users/jens/Library/Python/2.7/lib/python/site-packages/easybuild_framework-2.0.0dev-py2.7.egg/easybuild/framework/easyconfig/tools.py", line 161, in _dep_graph
    dgr.add_edge((spec['module'], dep))
  File "build/bdist.macosx-10.6-intel/egg/pygraph/classes/digraph.py", line 164, in add_edge
pygraph.classes.exceptions.AdditionError: freeglut is missing from the node_neighbors table
```

running this  works fine:
```
easyconfigs (develop) $ eb --dep-graph=bla.txt f/FSL/FSL-5.0.8-intel-2015a.eb -r .
```

**Comment by JackPerdue** [comment]
In short... this probably needs to wait until after 2.6.0.  I think you're right in what I changed but I haven't been able (had time) to rebuild to verify (new semester here started Tuesday).  Same for any IBM XL .eb's I come up with based on this new approach to bootstrapping... probably won't make 2.6.  If someone has problems on RHEL5 we can always point them here (or something).

**Comment by JackPerdue** [comment]
Apologies for the spam Jens... my (now deleted) comment belonged here: https://github.com/hpcugent/easybuild-easyconfigs/issues/2241#issuecomment-172176703
