### ISSUE TITLE
install-EasyBuild-develop.sh => ImportError: No module named vsc.utils

### ISSUE THREAD

**Issue by malcook** [hpcugent/easybuild-framework#1204]
Following the step outlined here:

 http://easybuild.readthedocs.org/en/latest/Installation_Alternative.html#installation-of-latest-development-version

fails to install now missing dependency, resulting in:

```
 eb --version
Traceback (most recent call last):
  File "/tmp/n/opt/EasyBuild/easybuild-framework/easybuild/main.py", line 45, in <module>
    from easybuild.tools.build_log import EasyBuildError, init_logging, print_msg, print_error, stop_logging
  File "/tmp/n/opt/EasyBuild/easybuild-framework/easybuild/tools/build_log.py", line 38, in <module>
    from vsc.utils import fancylogger
ImportError: No module named vsc.utils
```

The workaround is not clear to me, being somewhat new to this exact fray.  Guessing, the following succeeds

```
pip install --install-option "--prefix=${HOME}/EasyBuild" http://github.com/hpcugent/vsc-base/archive/master.tar.gz
```

However, installing vsc-utils fails as
```
pip install --install-option "--prefix=${HOME}/EasyBuild" http://github.com/hpcugent/vsc-utils/archive/master.tar.gz
Downloading/unpacking http://github.com/hpcugent/vsc-util/archive/master.tar.gz
  HTTP error 406 while getting http://github.com/hpcugent/vsc-util/archive/master.tar.gz
  Could not install requirement http://github.com/hpcugent/vsc-util/archive/master.tar.gz because of error HTTP Error 406: Not Acceptable
Could not install requirement http://github.com/hpcugent/vsc-util/archive/master.tar.gz because of HTTP error HTTP Error 406: Not Acceptable for URL http://github.com/hpcugent/vsc-util/archive/master.tar.gz
Storing complete log in /home/mec/.pip/pip.log
bash-4.1$ pip install --install-option "--prefix=${HOME}/EasyBuild" http://github.com/hpcugent/vsc-utils/archive/master.tar.gz
Downloading/unpacking http://github.com/hpcugent/vsc-utils/archive/master.tar.gz
  Downloading master.tar.gz
  Running setup.py egg_info for package from http://github.com/hpcugent/vsc-utils/archive/master.tar.gz
    vsc.install could not be found, make sure a recent vsc-base is installed
    you might want to try 'easy_install [--user] https://github.com/hpcugent/vsc-base/archive/master.tar.gz'
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-V0Tgy6-build/setup.py", line 46, in <module>
        shared_setup.remove_extra_bdist_rpm_files = remove_bdist_rpm_source_file
    NameError: name 'shared_setup' is not defined
    Complete output from command python setup.py egg_info:
    vsc.install could not be found, make sure a recent vsc-base is installed

you might want to try 'easy_install [--user] https://github.com/hpcugent/vsc-base/archive/master.tar.gz'

Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-V0Tgy6-build/setup.py", line 46, in <module>

    shared_setup.remove_extra_bdist_rpm_files = remove_bdist_rpm_source_file

NameError: name 'shared_setup' is not defined

```
correct workarounds much appreciated.... or fix my thinking here....

**Comment by malcook** [comment]
I worked around my issue  by installing vsc-utils and vsc-base into my system as:

```
sudo pip install --install-option http://github.com/hpcugent/vsc-base/archive/master.tar.gz
sudo pip install --install-option http://github.com/hpcugent/vsc-utils/archive/master.tar.gz
```

and now, happily, I get
```
eb --version
This is EasyBuild 2.0.0dev-rc458c322288975afff1bd589cc6b54e3d6259c17 (framework: 2.0.0dev-rc458c322288975afff1bd589cc6b54e3d6259c17, easyblocks: 2.0.0dev-r3aa69162b32d89da08fcd48080e95c3d9d531423) on host beta.sgc.loc.
bash-4.1$ 
```

... however this seems inconsistent with the spirit of what we're trying to accomplish.

Advice?

**Comment by malcook** [comment]
Further sleuthing and integrating what I've been learning suggests that an update PYTHONPATH between installing vsc-base and vsc-utils fixes this problem, and it does.

Leaving the new mantra as:

```
pip install --install-option "--prefix=${HOME}/EasyBuild" http://github.com/hpcugent/vsc-base/archive/master.tar.gz
easybuild_python_lib=$(python -c "import distutils.sysconfig; print distutils.sysconfig.get_python_lib(prefix='${HOME}/EasyBuild/');")
export PYTHONPATH=${easybuild_python_lib}:$PYTHONPATH
pip install --install-option "--prefix=${HOME}/EasyBuild" http://github.com/hpcugent/vsc-utils/archive/master.tar.gz

curl -O https://raw.githubusercontent.com/hpcugent/easybuild-framework/master/easybuild/scripts/install-EasyBuild-develop.sh
bash install-EasyBuild-develop.sh hpcugent $HOME/EasyBuild ## N.B. repo-to-be-used & installation prefix
module load $HOME/EasyBuild/module-EasyBuild-develop
eb --version  ## This should ensure you have a reasonable instance of EasyBuild

```

**Comment by boegel** [comment]
Thanks for reporting this @malcook. These problems are caused by a recent change in the `develop` branch of the framework, see https://github.com/hpcugent/easybuild-framework/pull/1160.

The updated `install-EasyBuild-develop.sh` script available via the `develop` branch already fixes these issues (see https://github.com/hpcugent/easybuild-framework/tree/develop/easybuild/scripts).

The documentation has been updated accordingly, see the `develop` version of the docs: http://easybuild.readthedocs.org/en/develop/Installation_Alternative.html#installation-of-latest-development-version.

There's no need to install `vsc-utils`, it's name is misleading. Only installing `vsc-base` (and having it available in `$PYTHONPATH`) suffices. But this is now tackled by the (develop version) of  `install-EasyBuild-develop.sh`.

Note the slightly different module name too, btw.

If this answers your questions, please close the issue (I try to stay away from (prematurely) closing issues other people have opened).

**Comment by malcook** [comment]
Hmmm.  Something is not right.

Following your updated wiki instructions at http://easybuild.readthedocs.org/en/develop/Installation_Alternative.html#installation-of-latest-development-version 

I still get 
```
ImportError: No module named vsc.utils
```
and the module name is still "module-EasyBuild-develop"

**Comment by malcook** [comment]
Fix confirmed  now (before I had missed instructures to first clone repo on github).
