### ISSUE TITLE
extraneous comments at end of .eb file (e.g. # EOF) break 2.3.0

### ISSUE THREAD

**Issue by JackPerdue** [hpcugent/easybuild-framework#1380]
re: my email of 9/3/2015

https://lists.ugent.be/wws/arc/easybuild/2015-09/msg00026.html

Having an extraneous comment at end of an easyconfig file causes EB/2.3.0 to barf with:

== temporary log file in case of crash /tmp/eb-PT_Dtr/easybuild-E1Tye9.log
Traceback (most recent call last):
  File "/software/easybuild/software/EasyBuild/2.3.0/lib/python2.6/site-packages/easybuild_framework-2.3.0-py2.6.egg/easybuild/main.py", line 354, in <module>
    main()
  File "/software/easybuild/software/EasyBuild/2.3.0/lib/python2.6/site-packages/easybuild_framework-2.3.0-py2.6.egg/easybuild/main.py", line 269, in main
    easyconfigs, generated_ecs = parse_easyconfigs(paths)
  File "/software/easybuild/software/EasyBuild/2.3.0/lib/python2.6/site-packages/easybuild_framework-2.3.0-py2.6.egg/easybuild/framework/easyconfig/tools.py", line 341, in parse_easyconfigs
    ecs = process_easyconfig(ec_file, **kwargs)
  File "/software/easybuild/software/EasyBuild/2.3.0/lib/python2.6/site-packages/easybuild_framework-2.3.0-py2.6.egg/easybuild/framework/easyconfig/easyconfig.py", line 941, in process_easyconfig
    ec = EasyConfig(spec, build_specs=build_specs, validate=validate, hidden=hidden)
  File "/software/easybuild/software/EasyBuild/2.3.0/lib/python2.6/site-packages/easybuild_framework-2.3.0-py2.6.egg/easybuild/framework/easyconfig/easyconfig.py", line 187, in __init__
    self.parser = EasyConfigParser(filename=self.path, rawcontent=self.rawtxt)
  File "/software/easybuild/software/EasyBuild/2.3.0/lib/python2.6/site-packages/easybuild_framework-2.3.0-py2.6.egg/easybuild/framework/easyconfig/parser.py", line 102, in __init__
    self._formatter.extract_comments(self.rawcontent)
  File "/software/easybuild/software/EasyBuild/2.3.0/lib/python2.6/site-packages/easybuild_framework-2.3.0-py2.6.egg/easybuild/framework/easyconfig/format/one.py", line 308, in extract_comments
    rawline = rawlines.pop(0)
IndexError: pop from empty list

**Comment by boegel** [comment]
#1381 should fix this, let's follow this up there
