### ISSUE TITLE
installation of Python 2.7.3 under toolchain goolf-1.4.10 gives the following errormessage "ImportError : No module named _random" 

### ISSUE THREAD

**Issue by tom6** [hpcugent/easybuild-framework#1543]
Environment (SLES 11 SP3 HPC cluster of 112 nodes)
---------------------------------------------------
```
eb@hpca-login:~> python -V
Python 2.6.9
eb@hpca-login:~> type module
module is a function
module () 
{ 
    eval $($LMOD_CMD bash "$@");
    [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)
}
eb@hpca-login:~> type -f module
-bash: type: module: not found
eb@hpca-login:~> module --version

Modules based on Lua: Version 6.0.1  2015-06-10 16:45
    by Robert McLay mclay@tacc.utexas.edu

eb@hpca-login:~> module av EasyBuild

eb@hpca-login:~> which -a eb
/space/hpc-apps/meteo/eb/easybuild/2.5.0/software/EasyBuild/2.5.0/bin/eb
eb@hpca-login:~> eb --version
This is EasyBuild 2.5.0 (framework: 2.5.0, easyblocks: 2.5.0) on host hpca-login.


eb@hpca-login:~> less .bashrc


export MODULEPATH=/space/hpc-apps/modules/meteo:/space/hpc-apps/meteo/eb/easybuild/2.5.0/modules/all:$MODULEPATH
module load lmod
source /space/hpc-apps/meteo/lmod/lmod/init/profile

module load EasyBuild

eb@hpca-login:~> cat .config/easybuild/config.cfg 
[config]
modules-tool=Lmod
buildpath=/dev/shm
installpath-modules=/space/hpc-apps/meteo/eb/easybuild/2.5.0/modules
installpath-software=/space/hpc-apps/meteo/eb/easybuild/2.5.0/software
sourcepath=/space/hpc-apps/meteo/eb/easybuild/2.5.0/sources
```

Situation where the installation fails:
----------------------------------------
After the installation of the toolchain goolf-1.4.10 which succeeds, we bumped into the following problem with installation of Python-2.7.3
We also tried other python versions with the same behaviour.

You can find the details in the attached log.
[easybuild-Python-2.7.3-20160113.155853.vPNLJ.txt](https://github.com/hpcugent/easybuild-framework/files/89133/easybuild-Python-2.7.3-20160113.155853.vPNLJ.txt)

**Comment by boegel** [comment]
@tom6: can you provide a *debug* log instead (use `eb --debug`)?

**Comment by boegel** [comment]
This seems to be the culprit:

```
gcc -L/space/hpc-apps/meteo/eb/easybuild/2.5.0/software/GCC/4.7.2/lib64 -L/space/hpc-apps/meteo/eb/easybuild/2.5.0/software/GCC/4.7.2/lib -L/space/hpc-apps/meteo/eb/easybuild/2.5.0/software/OpenBLAS/0.2.6-gompi-1.4.10-LAPACK-3.4.2/lib -L/space/hpc-apps/meteo/eb/easybuild/2.5.0/software/ScaLAPACK/2.0.2-gompi-1.4.10-OpenBLAS-0.2.6-LAPACK-3.4.2/lib -L/space/hpc-apps/meteo/eb/easybuild/2.5.0/software/FFTW/3.3.3-gompi-1.4.10/lib -L/space/hpc-apps/meteo/eb/easybuild/2.5.0/software/bzip2/1.0.6-goolf-1.4.10/lib -L/space/hpc-apps/meteo/eb/easybuild/2.5.0/software/zlib/1.2.7-goolf-1.4.10/lib -L/space/hpc-apps/meteo/eb/easybuild/2.5.0/software/libreadline/6.2-goolf-1.4.10/lib -L/space/hpc-apps/meteo/eb/easybuild/2.5.0/software/ncurses/5.9-goolf-1.4.10/lib -Xlinker -export-dynamic -o python \
			Modules/python.o \
			-L. -lpython2.7 -ldl -lm -lpthread -lutil /space/hpc-apps/meteo/eb/easybuild/2.5.0/software/libreadline/6.2-goolf-1.4.10/lib/libreadline.a /space/hpc-apps/meteo/eb/easybuild/2.5.0/software/ncurses/5.9-goolf-1.4.10/lib/libncurses.a   -lm  
/usr/bin/ld: build/temp.linux-x86_64-2.7/dev/shm/Python/2.7.3/goolf-1.4.10/Python-2.7.3/Modules/_randommodule.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
build/temp.linux-x86_64-2.7/dev/shm/Python/2.7.3/goolf-1.4.10/Python-2.7.3/Modules/_randommodule.o: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
/dev/shm/Python/2.7.3/goolf-1.4.10/Python-2.7.3/Modules/_collectionsmodule.c: In function ‘deque_clearmethod’:
/dev/shm/Python/2.7.3/goolf-1.4.10/Python-2.7.3/Modules/_collectionsmodule.c:707:9: warning: variable ‘rv’ set but not used [-Wunused-but-set-variable]
/dev/shm/Python/2.7.3/goolf-1.4.10/Python-2.7.3/Modules/socketmodule.c: In function ‘socket_gethostbyname_ex’:
/dev/shm/Python/2.7.3/goolf-1.4.10/Python-2.7.3/Modules/socketmodule.c:3374:9: warning: variable ‘result’ set but not used [-Wunused-but-set-variable]
/dev/shm/Python/2.7.3/goolf-1.4.10/Python-2.7.3/Modules/socketmodule.c: In function ‘socket_gethostbyaddr’:
/dev/shm/Python/2.7.3/goolf-1.4.10/Python-2.7.3/Modules/socketmodule.c:3450:9: warning: variable ‘result’ set but not used [-Wunused-but-set-variable]
```

Can you check whether your `libreadline` module was built with `-fPIC`?

**Comment by boegel** [comment]
Or maybe it's `ncurses`, not sure. Hmm, this looks a bit weird. You may need to build Python *itself* with `-fPIC` enabled.

Enabling the use of `-fPIC` is done by including `'pic': True` in `toolchainopts` in the easyconfig file, e.g.:

```python
toolchainopts = {'pic': True}
```

**Comment by ladc** [comment]
Perhaps related to the following bug:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57777

**Comment by ladc** [comment]
Is it possible to force ``-O2``, just to check?

**Comment by boegel** [comment]
@ladc: waw, nice catch! That sure looks like the problem.

You can make `eb` use `-O2` by changing `toolchainopts` in the easyconfig file:

```python
toolchainopts = {'defaultopt': True}
```

(the default corresponds to having `opt` enabled, which corresponds to `-O3`, cfr. https://github.com/hpcugent/easybuild-framework/blob/master/easybuild/tools/toolchain/compiler.py#L97

**Comment by tom6** [comment]
Hi, thx everyone for your fast and accurate input.
i have adapted the eb conf of Python 2.7.3 to the following

```
toolchain = {'name': 'goolf', 'version': '1.4.10'}
#toolchainopts = {'pic': True, 'opt': True, 'optarch': True}
toolchainopts = {'pic': True, 'defaultopt': True, 'optarch': True}
```
result: 
-------
still the same error..
@boegel: libreadline6.2 was installed with  toolchainopts = {'pic': True}

```
eb@hpca-login:~> eb --debug /space/hpc-apps/meteo/eb/easybuild/2.5.0/software/EasyBuild/2.5.0/lib64/python2.6/site-packages/easybuild_easyconfigs-2.5.0-py2.6.egg/easybuild/easyconfigs/p/Python/Python-2.7.3-goolf-1.4.10.eb --robot
== temporary log file in case of crash /tmp/eb-SFywAT/easybuild-9LGkXu.log
== resolving dependencies ...
== processing EasyBuild easyconfig /space/hpc-apps/meteo/eb/easybuild/2.5.0/software/EasyBuild/2.5.0/lib64/python2.6/site-packages/easybuild_easyconfigs-2.5.0-py2.6.egg/easybuild/easyconfigs/p/Python/Python-2.7.3-goolf-1.4.10.eb
== building and installing Python/2.7.3-goolf-1.4.10...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/Python/2.7.3/goolf-1.4.10): build failed (first 300 chars): cmd " python setup.py install --prefix=/space/hpc-apps/meteo/eb/easybuild/2.5.0/software/Python/2.7.3-goolf-1.4.10 " exited with exitcode 1 and output:
running install
Traceback (most recent call last):
  File "setup.py", line 94, in <module>
    scripts = scripts,
  File "/space/hpc-apps/meteo/eb/e
== Results of the build can be found in the log file /tmp/eb-SFywAT/easybuild-Python-2.7.3-20160114.084824.lWPPr.log
ERROR: Build of /space/hpc-apps/meteo/eb/easybuild/2.5.0/software/EasyBuild/2.5.0/lib64/python2.6/site-packages/easybuild_easyconfigs-2.5.0-py2.6.egg/easybuild/easyconfigs/p/Python/Python-2.7.3-goolf-1.4.10.eb failed (err: 'build failed (first 300 chars): cmd " python setup.py install --prefix=/space/hpc-apps/meteo/eb/easybuild/2.5.0/software/Python/2.7.3-goolf-1.4.10 " exited with exitcode 1 and output:\nrunning install\nTraceback (most recent call last):\n  File "setup.py", line 94, in <module>\n    scripts = scripts,\n  File "/space/hpc-apps/meteo/eb/e')
```

Any other suggestions?
[easybuild-Python-2.7.3-20160114.084824.lWPPr.txt](https://github.com/hpcugent/easybuild-framework/files/90110/easybuild-Python-2.7.3-20160114.084824.lWPPr.txt)

**Comment by tom6** [comment]
I succeed to successfully build Python-2.7.10 with toolchain **goolf-1.7.20**


[easybuild-Python-2.7.10-20160115.155425.txt](https://github.com/hpcugent/easybuild-framework/files/92149/easybuild-Python-2.7.10-20160115.155425.txt)

**Comment by ladc** [comment]
Thanks! Probably a compiler bug in 4.7 then, which also persisted with
`-O2`...

**Comment by boegel** [comment]
@ladc: what if you bring down the optimization level even further? `lowopt` is -O1, `noopt` is -O0 (but I wouldn't recommend the latter for a production installation)

**Comment by tom6** [comment]
@boegel : i already tried that to with the same error message

**Comment by boegel** [comment]
@tom6: OK, then I'm out of ideas... This seems to be a weird bug in GCC, indeed.

So, why are you building and old Python 2.7.x with an old toolchain?

I would recommend the `foss` toolchain above `goolf`, which is (currently) basically the same except that in the latest `foss` versions we also include `binutils`.

**Comment by ladc** [comment]
@boegel: In principle to have the same environment as on another machine (and also to make sure the same modules are available in the same versions)

**Comment by tom6** [comment]
@boegel and @ladc : thanks for all your input. We can close the ticket since i succeed to install all the necessary software tools under toolchain goolf-1.7.20.
