### ISSUE TITLE
Failed to find pattern \'^\./easybuild_framework-2.6\'

### ISSUE THREAD

**Issue by eediaz1987** [hpcugent/easybuild-framework#1598]
Tries to find easybuild_framework with local path while it is only there with an absolute path. Even when it tells according to the log file that it removed the absolute path:

== sanity checking...
== FAILED: Installation ended unsuccessfully (build directory: /tmp/tmpuS0WXi/EasyBuild/2.6.0/dummy-dummy): build failed (first 300 chars): Failed to find pattern '^\./easybuild_framework-2.6' in /home/ernesto/easybuild/software/EasyBuild/2.6.0/lib/python2.7/site-packages/easy-install.pth: import sys; sys.__plen = len(sys.path)
/usr/local/lib/python2.7/dist-packages/vsc_install-0.9.12-py2.7.egg
/usr/local/lib/python2.7/dist-packages/set
== Results of the build can be found in the log file /tmp/eb-n222jj/easybuild-EasyBuild-2.6.0-20160208.122230.FfBSf.log
Traceback (most recent call last):
  File "bootstrap_eb.py", line 715, in <module>
    main()
  File "bootstrap_eb.py", line 534, in main
    stage2(tmpdir, templates, install_path, distribute_egg_dir, sourcepath)
  File "bootstrap_eb.py", line 452, in stage2
    easybuild_main()
  File "/tmp/tmpuS0WXi/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.6.0-py2.7.egg/easybuild/main.py", line 350, in main
    ecs_with_res = build_and_install_software(ordered_ecs, init_session_state, exit_on_failure=exit_on_failure)
  File "/tmp/tmpuS0WXi/eb_stage1/lib/python2.7/site-packages/easybuild_framework-2.6.0-py2.7.egg/easybuild/main.py", line 148, in build_and_install_software
    raise EasyBuildError(test_msg)
easybuild.tools.build_log.EasyBuildError: 'Build of /tmp/tmpuS0WXi/EasyBuild-2.6.0.eb failed (err: "build failed (first 300 chars): Failed to find pattern \'^\\\\./easybuild_framework-2.6\' in /home/ernesto/easybuild/software/EasyBuild/2.6.0/lib/python2.7/site-packages/easy-install.pth: import sys; sys.__plen = len(sys.path)\\n/usr/local/lib/python2.7/dist-packages/vsc_install-0.9.12-py2.7.egg\\n/usr/local/lib/python2.7/dist-packages/set")'

== 2016-02-08 12:00:56,690 bootstrap_eb.EB_EasyBuildMeta INFO Running method post_install_step part of step postproc
== 2016-02-08 12:00:56,692 bootstrap_eb.EB_EasyBuildMeta WARNING Found /home/ernesto/easybuild/software/EasyBuild/2.6.0/lib/python2.7/site-packages/setuptools.pth, and includes one or more absolute system paths. Removing it.
== 2016-02-08 12:00:56,694 bootstrap_eb.EB_EasyBuildMeta INFO sanity checking...
== 2016-02-08 12:00:56,695 bootstrap_eb.EB_EasyBuildMeta INFO Starting sanitycheck step
== 2016-02-08 12:00:56,704 bootstrap_eb.EB_EasyBuildMeta INFO Running method sanity_check_step part of step sanitycheck
== 2016-02-08 12:00:56,719 bootstrap_eb ERROR Failed to find pattern '^\./easybuild_framework-2.6' in /home/ernesto/easybuild/software/EasyBuild/2.6.0/lib/python2.7/site-packages/easy-install.pth: import sys; sys.__plen = len(sys.path)
/usr/local/lib/python2.7/dist-packages/vsc_install-0.9.12-py2.7.egg
/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg
/usr/local/lib/python2.7/dist-packages/easybuild_framework-2.6.0-py2.7.egg
./easybuild_easyconfigs-2.6.0-py2.7.egg
/usr/local/lib/python2.7/dist-packages/easybuild_easyblocks-2.6.0-py2.7.egg
./vsc_base-2.4.16-py2.7.egg
import sys; new=sys.path[sys.__plen:]; del sys.path[sys.__plen:]; p=getattr(sys,'__egginsert',0); sys.path[p:p]=new; sys.__egginsert = p+len(new)
 (at easybuild/easyblocks/e/easybuildmeta.py:132 in sanity_check_step)

**Comment by boegel** [comment]
@eediaz1987: the check is failing with good reason... the `easy-install.pth` file is picking up paths from the system, even though things are being installed in a prefix

Which EasyBuild version are you using here, and where/how was it installed?

This looks very much like a problem we tried to solve in EasyBuild v2.6.0, but since that's the one you're installing, that's probably not the version you're using?

**Comment by eediaz1987** [comment]
i was installing the last version EasyBuild from git, the OS used was mint rafaela dist

**Comment by boegel** [comment]
@eediaz1987: the bootstrap is picking up an EasyBuild 2.6.0 installed which is available system-wide in `/usr/local/lib/python2.7/dist-packages`.

Do you know who installed it there, and how?

**Comment by eediaz1987** [comment]
i probably done unintentionally trying to resolve an error that i had before

2016-02-13 4:15 GMT-05:00 Kenneth Hoste <notifications@github.com>:

**Comment by boegel** [comment]
OK, then I suggest you remove the `easybuild` and `vsc` `.egg` directories in `/usr/local/lib/python2.7/dist-packages`

**Comment by eediaz1987** [comment]
thanks, i will do that,

**Comment by boegel** [comment]
@eediaz1987 If you consider this problem as being resolved, please close this issue.

It's very hard to prevent that packages that are available system-wide already are picked up...
