### ISSUE TITLE
broken tests on Python 2.6 because latest GitPython is no longer py2.6 compatible

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild-framework#1780]
```
======================================================================
ERROR: Test use of --new-pr (dry run only).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/boegel/easybuild-framework/test/framework/options.py", line 2252, in test_new_update_pr
    self.eb_main(args, do_build=True, raise_error=True, testing=False)
  File "/home/travis/build/boegel/easybuild-framework/test/framework/utilities.py", line 276, in eb_main
    raise myerr
EasyBuildError: "ImportError: cannot import name OrderedDict; required module 'git' is not available (provided by Python package GitPython, available from https://pypi.python.org/pypi/GitPython)"
----------------------------------------------------------------------
```

cfr. https://github.com/gitpython-developers/GitPython/pull/431/files#r64649040

**Comment by boegel** [comment]
the issue with the `OrderedDict` import was fixed in https://github.com/gitpython-developers/GitPython/pull/433 (to be included in GitPython 2.0.4?), but since GitPython 2.x is officially no longer compatible with Python 2.6 (cfr. https://github.com/gitpython-developers/GitPython/blob/master/doc/source/changes.rst#200---features), it's better to stick to the latest GitPython 1.x on top of Python 2.6, see #1781
