### ISSUE TITLE
Failure, Issue when update Easybuild 1.10.1 packages (framework, easyblocks, easyconfigs) to the latest 2.8.2

### ISSUE THREAD

**Issue by tom6** [hpcugent/easybuild-framework#1857]
Environment (CentOS 6.5 ) - 64 cores - Linux gloin.oma.be 2.6.32-431.29.2.el6.x86_64 #1 SMP Tue Sep 9 21:36:05 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
---------------------------------------------------------------------------------------------------------------------------
```
[root@gloin ~]# python -V
Python 2.6.6
[eb@gloin ~]$ type module
module is a function
module () 
{ 
    eval `/usr/bin/modulecmd bash $*`
}

[eb@gloin ~]$  module --version
VERSION=3.2.10
DATE=2012-12-21

AUTOLOADPATH=undef
BASEPREFIX="/usr/share"
BEGINENV=99
CACHE_AVAIL=undef
DEF_COLLATE_BY_NUMBER=undef
DOT_EXT=""
EVAL_ALIAS=1
HAS_BOURNE_FUNCS=1
HAS_BOURNE_ALIAS=1
HAS_TCLXLIBS=undef
HAS_X11LIBS=1
LMSPLIT_SIZE=1000
MODULEPATH="/etc/modulefiles"
MODULES_INIT_DIR="/usr/share/Modules/init"
PREFIX="/usr/share/Modules"
TCL_VERSION="8.5"
TCL_PATCH_LEVEL="8.5.7"
TMP_DIR="/tmp"
USE_FREE=undef
VERSION_MAGIC=1
VERSIONPATH=undef
WANTS_VERSIONING=0
WITH_DEBUG_INFO=undef

[eb@gloin ~]$  module av EasyBuild
[eb@gloin ~]$ which -a eb
~/bin/eb
~/bin/eb

[eb@gloin ~]$  eb --version
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/opt/eb/lib/python2.6/site-packages/easybuild/main.py", line 47, in <module>
    from easybuild.tools.build_log import EasyBuildError, init_logging, print_msg, print_error, stop_logging
  File "/opt/eb/lib/python2.6/site-packages/easybuild/tools/build_log.py", line 39, in <module>
    from vsc.utils import fancylogger
ImportError: No module named vsc.utils


[eb@gloin ~]$ cat .bashrc 
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
[eb@gloin ~]$ cat .bash_profile 
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin:/opt/dell/srvadmin/sbin:/opt/eb/bin
PYTHONPATH=/opt/eb/lib/python2.6/site-packages
MODULEPATH=$MODULEPATH
#
export PATH 
export PYTHONPATH
export MODULEPATH
#
export C_INCLUDE_PATH=/usr/include/gdal
export CPLUS_INCLUDE_PATH=/usr/include/gda

```
Situation where the binary eb does not seem to work anymore:
---------------------------------------------------------------------------------
* The update procedure
```
[root@gloin bin]# pip install --install-option "--prefix=/opt/eb" easybuild -U
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
/usr/lib/python2.6/site-packages/pip/commands/install.py:180: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting easybuild
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached easybuild-2.8.2.tar.gz
Collecting easybuild-easyconfigs==2.8.2 (from easybuild)
  Using cached easybuild-easyconfigs-2.8.2.tar.gz
Collecting easybuild-easyblocks==2.8.2 (from easybuild)
  Using cached easybuild-easyblocks-2.8.2.tar.gz
Collecting easybuild-framework==2.8.2 (from easybuild)
  Using cached easybuild-framework-2.8.2.tar.gz
Requirement already up-to-date: setuptools>=0.6 in /usr/lib/python2.6/site-packages (from easybuild-easyblocks==2.8.2->easybuild)
Collecting vsc-install>=0.9.19 (from easybuild-framework==2.8.2->easybuild)
  Using cached vsc-install-0.10.11.tar.gz
Collecting vsc-base>=2.4.18 (from easybuild-framework==2.8.2->easybuild)
  Using cached vsc-base-2.5.1.tar.gz
Installing collected packages: vsc-install, vsc-base, easybuild-framework, easybuild-easyblocks, easybuild-easyconfigs, easybuild
  Running setup.py install for vsc-install ... done
  Running setup.py install for vsc-base ... done
  Running setup.py install for easybuild-framework ... done
  Running setup.py install for easybuild-easyblocks ... done
  Running setup.py install for easybuild-easyconfigs ... done
  Running setup.py install for easybuild ... done
Successfully installed easybuild easybuild-easyblocks easybuild-easyconfigs easybuild-framework vsc-base vsc-install

```
* check if eb is still working :(
```
[root@gloin bin]# su - eb
[eb@gloin ~]$ eb --version
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/opt/eb/lib/python2.6/site-packages/easybuild/main.py", line 47, in <module>
    from easybuild.tools.build_log import EasyBuildError, init_logging, print_msg, print_error, stop_logging
  File "/opt/eb/lib/python2.6/site-packages/easybuild/tools/build_log.py", line 39, in <module>
    from vsc.utils import fancylogger
ImportError: No module named vsc.utils

```

* try to reinstall vcs-utils

```
[root@gloin bin]# pip install --install-option "--prefix=/opt/eb" http://github.com/hpcugent/vsc-utils/archive/master.tar.gz

DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
/usr/lib/python2.6/site-packages/pip/commands/install.py:180: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting http://github.com/hpcugent/vsc-utils/archive/master.tar.gz
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading http://github.com/hpcugent/vsc-utils/archive/master.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-S13TXE-build/setup.py", line 33, in <module>
        import vsc.install.shared_setup as shared_setup
    ImportError: No module named vsc.install.shared_setup
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-S13TXE-build/

```

**Comment by ocaisa** [comment]
I'm maybe not the right one to respond to this but Kenneth is off sunning
himself so I'll give you some feedback at least.

vsc-utils is a hard requirement for eb for some time, you either need to
install it with pip (not sure how update works with pip but it looks like
its not pulling in additional deps) or use the bootstrapping method to
install the latest version.

Alan

**Comment by tom6** [comment]
The issue is solved. 
It seemed that my PYTHONPATH after the update needed to be updated.
Before update it was 
/usr/lib/python2.6/site-packages

After Update : 
**/opt/eb/lib/python2.6/site-packages:/usr/lib/python2.6/site-packages**

Now i can again use the easybuild binary! :) 
```
[eb@gloin ~]$ eb --version
This is EasyBuild 2.8.2 (framework: 2.8.2, easyblocks: 2.8.2) on host gloin.oma.be.
```

**Comment by boegel** [comment]
Note that the actual dependency is `vsc-base`, not `vsc-utils` (the latter does exist, but doesn't provide what EB requires).

See also http://easybuild.readthedocs.io/en/latest/Installation.html#required-python-packages and http://easybuild.readthedocs.io/en/latest/Release_notes.html#v2-0-0-march-6th-2015 where it's mentioned that the EasyBuild framework repo does not include a copy of vsc-base anymore.
