### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Colorize'

### ISSUE THREAD

**Issue by jgphpc** [hpcugent/easybuild-framework#1900]
Hi,

Trying to install eb on a new system but i get: `'module' object has no attribute 'Colorize'`

* eb -h
```
Traceback (most recent call last):
  File "/usr/common/software/python/2.7.9/lib/python2.7/runpy.py", line 162, in
 _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/common/software/python/2.7.9/lib/python2.7/runpy.py", line 72, 
in _run_code
    exec code in run_globals
  File "/global/u1/p/piccinal/DELETE/EB/easybuild-framework/easybuild/main.py", line 47,
 in <module>
    from easybuild.tools.build_log import EasyBuildError,
 init_logging, print_msg, print_error, stop_logging
  File "/global/u1/p/piccinal/DELETE/EB/easybuild-framework/easybuild/tools/build_log.py", 
line 200, 
in <module>
    def init_logging(logfile, logtostdout=False, silent=False, colorize=fancylogger.Colorize.AUTO):
AttributeError: 'module' object has no attribute 'Colorize'
```

I am lost because it looks like `Colorize` is installed:
* pip install --user Colorize
```
Requirement already satisfied (use --upgrade to upgrade): 
Colorize in 
/global/u1/p/piccinal/.local/edison/2.7.9/lib/python2.7/site-packages 
<--- in my $PYTHONPATH
```

* Same issue with `eb --color=never -h`
Any hint please ?

**Comment by jgphpc** [comment]
Installing the bootstrap version instead of the dev. version fixes my issue.

**Comment by boegel** [comment]
@jgphpc see also https://github.com/hpcugent/easybuild-framework/pull/1898, you need to update `vsc-base` to the latest release or `master` if you're using EasyBuild framework `develop`
