### ISSUE TITLE
Compiling Tcl with intel-2016b toolchain on Ubuntu 16.04 results in segmenation fault

### ISSUE THREAD

**Issue by riccardomurri** [hpcugent/easybuild-framework#1936]
Trying to compile Tcl-8.6.4 with the `intel-2016b` toolchain on Ubuntu 16.04
ends with a "Segmentation fault" error during the test phase. This is the
relevant part from EB's log file::

    make[1]: Leaving directory '/tmp/Tcl/8.6.4/intel-2016b/tcl8.6.4/unix'
    LD_LIBRARY_PATH=`pwd`:/opt/easybuild/software/zlib/1.2.8/lib:/opt/easybuild/software/imkl/11.3.3.210-iimpi-2016b/mkl/lib/intel64:/opt/easybuild/software/imkl/11.3.3.210-iimpi-2016b/lib/intel64:/opt/easybuild/software/impi/5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26/lib64:/opt/easybuild/software/ifort/2016.3.210-GCC-5.4.0-2.26/compilers_and_libraries_2016.3.210/linux/mpi/intel64:/opt/easybuild/software/ifort/2016.3.210-GCC-5.4.0-2.26/compilers_and_libraries_2016.3.210/linux/compiler/lib/intel64:/opt/easybuild/software/ifort/2016.3.210-GCC-5.4.0-2.26/lib/intel64:/opt/easybuild/software/ifort/2016.3.210-GCC-5.4.0-2.26/lib:/opt/easybuild/software/icc/2016.3.210-GCC-5.4.0-2.26/compilers_and_libraries_2016.3.210/linux/compiler/lib/intel64:/opt/easybuild/software/icc/2016.3.210-GCC-5.4.0-2.26/lib/intel64:/opt/easybuild/software/icc/2016.3.210-GCC-5.4.0-2.26/lib:/opt/easybuild/software/binutils/2.26-GCCcore-5.4.0/lib:/opt/easybuild/software/GCCcore/5.4.0/lib/gcc/x86_64-unknown-linux-gnu/5.4.0:/opt/easybuild/software/GCCcore/5.4.0/lib64:/opt/easybuild/software/GCCcore/5.4.0/lib TCLLIBPATH="/tmp/Tcl/8.6.4/intel-2016b/tcl8.6.4/unix/pkgs" TCL_LIBRARY="/tmp/Tcl/8.6.4/intel-2016b/tcl8.6.4/library" ./tcltest /tmp/Tcl/8.6.4/intel-2016b/tcl8.6.4/tests/all.tcl
    Segmentation fault (core dumped)
    Makefile:715: recipe for target 'test-tcl' failed
    make: *** [test-tcl] Error 139
     (at easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_framework-2.9.0-py2.7.egg/easybuild/tools/run.py:438 in parse_cmd_output)

Print the failed traceback with `gdb` shows that the failure happens quite
early, actually before any code from `tcltest` is executed::

    $ LD_LIBRARY_PATH="...as above..." TCLLIBPATH="/tmp/Tcl/8.6.4/intel-2016b/tcl8.6.4/unix/pkgs" TCL_LIBRARY="/tmp/Tcl/8.6.4/intel-2016b/tcl8.6.4/library" gdb -ex r --args ./tcltest '/tmp/Tcl/8.6.4/intel-2016b/tcl8.6.4/tests/all.tcl'
    GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
    [...]
    Reading symbols from ./tcltest...(no debugging symbols found)...done.
    Starting program: /tmp/Tcl/8.6.4/intel-2016b/tcl8.6.4/unix/tcltest /tmp/Tcl/8.6.4/intel-2016b/tcl8.6.4/tests/all.tcl

    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff69f7729 in ?? ()
    (gdb) bt
    #0  0x00007ffff69f7729 in ?? ()
    #1  0x00007ffff7de4423 in elf_machine_rela (skip_ifunc=<optimized out>, reloc_addr_arg=<optimized out>, version=0x0, sym=<optimized out>, reloc=0x7ffff4f86e38, map=0x7ffff7fd2050)
        at ../sysdeps/x86_64/dl-machine.h:310
    #2  elf_dynamic_do_Rela (skip_ifunc=<optimized out>, lazy=<optimized out>, nrelative=<optimized out>, relsize=<optimized out>, reladdr=<optimized out>, map=0x7ffff7fd2050) at do-rel.h:170
    #3  _dl_relocate_object (scope=<optimized out>, reloc_mode=<optimized out>, consider_profiling=<optimized out>, consider_profiling@entry=0) at dl-reloc.c:258
    #4  0x00007ffff7ddaf5b in dl_main (phdr=<optimized out>, phnum=<optimized out>, user_entry=<optimized out>, auxv=<optimized out>) at rtld.c:2072
    #5  0x00007ffff7df0462 in _dl_sysdep_start (start_argptr=start_argptr@entry=0x7fffffffd910, dl_main=dl_main@entry=0x7ffff7dd89a0 <dl_main>) at ../elf/dl-sysdep.c:249
    #6  0x00007ffff7ddbe7a in _dl_start_final (arg=0x7fffffffd910) at rtld.c:307
    #7  _dl_start (arg=0x7fffffffd910) at rtld.c:413
    #8  0x00007ffff7dd7cc8 in _start () from /lib64/ld-linux-x86-64.so.2
    #9  0x0000000000000002 in ?? ()
    #10 0x00007fffffffdc50 in ?? ()
    #11 0x00007fffffffdc81 in ?? ()
    #12 0x0000000000000000 in ?? ()
    (gdb) quit

This *may* be the result of some incompatibility between the "intel/2016b"
compilers and Ubuntu 16.04, but more evidence should be gathered.

**Comment by boegel** [comment]
@riccardomurri first thing I would do is see if this issue still exists in Tcl 8.6.5 and 8.6.6...

**Comment by riccardomurri** [comment]
Same issue in Tcl 8.6.5

**Comment by boegel** [comment]
@riccardomurri still there in 8.6.6 too?
