### ISSUE TITLE
eb --check-github goes down hard if 'git' module is not available

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild-framework#1968]
```
$ eb --check-github
== temporary log file in case of crash /tmp/eb-xWC1Af/easybuild-i2kMLd.log

Checking status of GitHub integration...

Making sure we're online... OK

* GitHub user... boegel => OK
* GitHub token... 7f6..743 (len: 40) => OK (validated)
* git command... OK ("git version 1.7.1; ")
* GitPython module... FAIL (import failed)
* push access to boegel/easybuild-easyconfigs repo @ GitHub...
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/vsc-mounts/gent-data/gvo000/gvo00002/vsc40023/easybuild_easy_installed/lib/python2.6/site-packages/easybuild_framework-3.0.0.dev0-py2.6.egg/easybuild/main.py", line 443, in <module>
    main()
  File "/vsc-mounts/gent-data/gvo000/gvo00002/vsc40023/easybuild_easy_installed/lib/python2.6/site-packages/easybuild_framework-3.0.0.dev0-py2.6.egg/easybuild/main.py", line 249, in main
    check_github()
  File "/data/gent/gvo000/gvo00002/vsc40023/easybuild_easy_installed/lib/python2.6/site-packages/easybuild_framework-3.0.0.dev0-py2.6.egg/easybuild/tools/github.py", line 1093, in check_github
    gp_ver, req_gp_ver = git.__version__, '1.0'
NameError: global name 'git' is not defined
```

**Comment by boegel** [comment]
fixed in #2085
