### ISSUE TITLE
TypeError exception while using bootstrap_eb.py

### ISSUE THREAD

**Issue by jbd** [hpcugent/easybuild-framework#1983]
Hello,

I'm trying bootstrap_eb.py from develop/e7fed028a529a2f2 as the documentation mentions (curl -O https://raw.githubusercontent.com/hpcugent/easybuild-framework/develop/easybuild/scripts/bootstrap_eb.py) and I've got this error if I'm trying to execute it from a clean docker environment :

```
Traceback (most recent call last):
  File "bootstrap_eb.py", line 953, in <module>
    main()
  File "bootstrap_eb.py", line 756, in main
    stage2(tmpdir, templates, install_path, distribute_egg_dir, sourcepath)
  File "bootstrap_eb.py", line 594, in stage2
    preinstallopts += "%s $(which easy_install) -U --prefix %(installdir)s setuptools && " % sys.executable
TypeError: format requires a mapping
```

The whole output of python bootstrap_eb.py $EASYBUILD_PREFIX is here : https://gist.github.com/jbd/7ddd6a1a665dc2333e9e9d1d073fed94

I've got no problem if I'm using the master (e65a6c9771cb6318) branch (https://raw.githubusercontent.com/hpcugent/easybuild-framework/master/easybuild/scripts/bootstrap_eb.py).

**Comment by boegel** [comment]
can you try changing ` %(installdir)s` to `% %(installdir)s` on the offending line?

**Comment by jbd** [comment]
No more luck, but a different error :

```
python bootstrap_eb.py $EASYBUILD_PREFIX 
[[INFO]] EasyBuild bootstrap script (version 20161104.01, MD5: 769aa7b23f2a66cec5f83072c88d63b5)
[[INFO]] Found Python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) ; [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]

[[INFO]] Installation prefix /soft/adm/easybuild
[[INFO]] Found module command '/soft/adm/lmod/lmod/libexec/lmod' via $LMOD_CMD (Lmod), so using it.
[[INFO]] No suitable setuptools installation found, proceeding with stage 0...


[[INFO]] +++ STAGE 0: installing distribute via included (patched) distribute_setup.py...

Downloading http://hpcugent.github.io/easybuild/files/distribute-0.6.49-patched1.tar.gz
Extracting in /tmp/tmpUSuQo1
Now working in /tmp/tmpUSuQo1/distribute-0.6.49
Installing Distribute
[[INFO]] Installed setuptools version 0.6 (/tmp/tmpCnzPN4/lib/python2.6/site-packages/distribute-0.6.49-py2.6.egg/setuptools/__init__.pyc)


[[INFO]] +++ STAGE 1: installing EasyBuild in temporary dir with easy_install...

[[INFO]] installing EasyBuild with 'easy_install --quiet --upgrade --prefix=/tmp/tmpCnzPN4/eb_stage1 easybuild'
[[INFO]] running post install command 'easy_install --upgrade --prefix=/tmp/tmpCnzPN4/eb_stage1 vsc-base'


[[INFO]] +++ STAGE 2: installing EasyBuild in /soft/adm/easybuild with EasyBuild from stage 1...

== temporary log file in case of crash /tmp/eb-uHUgi5/easybuild-BYa_i7.log
== processing EasyBuild easyconfig /tmp/tmpCnzPN4/EasyBuild-2.9.0.eb
== building and installing EasyBuild/2.9.0...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== FAILED: Installation ended unsuccessfully (build directory: /tmp/tmpCnzPN4/EasyBuild/2.9.0/dummy-dummy): build failed (first 300 chars): cmd "/usr/bin/python $(which easy_install) -U --prefix /soft/adm/easybuild/software/EasyBuild/2.9.0 setuptools && /usr/bin/python $(which easy_install) -U --prefix /soft/adm/easybuild/software/EasyBuild/2.9.0 vsc-install &&  /usr/bin/python setup.py install --prefix=/soft/adm/easybuild/software/Easy
== Results of the build can be found in the log file(s) /tmp/eb-uHUgi5/easybuild-EasyBuild-2.9.0-20161109.112340.xBYBF.log
Traceback (most recent call last):
  File "bootstrap_eb.py", line 953, in <module>
    main()
  File "bootstrap_eb.py", line 756, in main
    stage2(tmpdir, templates, install_path, distribute_egg_dir, sourcepath)
  File "bootstrap_eb.py", line 656, in stage2
    easybuild_main()
  File "/tmp/tmpCnzPN4/eb_stage1/lib/python2.6/site-packages/easybuild_framework-2.9.0-py2.6.egg/easybuild/main.py", line 411, in main
    ecs_with_res = build_and_install_software(ordered_ecs, init_session_state, exit_on_failure=exit_on_failure)
  File "/tmp/tmpCnzPN4/eb_stage1/lib/python2.6/site-packages/easybuild_framework-2.9.0-py2.6.egg/easybuild/main.py", line 150, in build_and_install_software
    raise EasyBuildError(test_msg)
easybuild.tools.build_log.EasyBuildError: 'Build of /tmp/tmpCnzPN4/EasyBuild-2.9.0.eb failed (err: \'build failed (first 300 chars): cmd "/usr/bin/python $(which easy_install) -U --prefix /soft/adm/easybuild/software/EasyBuild/2.9.0 setuptools && /usr/bin/python $(which easy_install) -U --prefix /soft/adm/easybuild/software/EasyBuild/2.9.0 vsc-install &&  /usr/bin/python setup.py install --prefix=/soft/adm/easybuild/software/Easy\')'
```

The full output is here : https://gist.github.com/jbd/de5061ffd9a7c72be7e8abd4071a44be

The interesting part is here :

```
Traceback (most recent call last):
  File "/tmp/tmpCnzPN4/bin/easy_install", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

From what I understand, if setuptools is not installed, the bootstrap script will install it at stage 0. Am I missing something ?

**Comment by jbd** [comment]
For what it worth, the Dockerfile using the master version of bootstrap_eb.py (working) : https://gist.github.com/jbd/efb178dde29056290c801c0b67f44d74

The Dockerfile using the develop version (not working) : https://gist.github.com/jbd/8e24ebf47261475748ca42cd1e5c8916

**Comment by boegel** [comment]
@jbd I was a bit too eager in cleaning up the bootstrap script in #1946, and removed a block of code that is required when `setuptools` is provided via stage 0.

We missed this because in our Travis setup `setuptools` *is* available, so stage 0 is skipped (which is new, the `master` version of the bootstrap script never skips `stage 0` automagically).

Please check if the updated bootstrap script in #1984 fixes the problems you're seeing.

**Comment by jbd** [comment]
Updated bootstrap script in #1984 fixes the problems for me. Cool !

**Comment by boegel** [comment]
@jbd Great, thanks for the feedback! I'll merge this ASAP, and also look into updating the tests so we test in an environment where `setuptools` is not available.
