### ISSUE TITLE
Problem with release update after upgrade to Fedora 25

### ISSUE THREAD

**Issue by verdurin** [hpcugent/easybuild-framework#2069]
I saw this error after trying to upgrade to `3.0.2` with the `--install-latest-eb-release` command:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/adam/.local/easybuild/software/EasyBuild/3.0.1/lib/python2.7/site-packages/easybuild_framework-3.0.1-py2.7.egg/easybuild/main.py", line 443, in <module>
    main()
  File "/home/adam/.local/easybuild/software/EasyBuild/3.0.1/lib/python2.7/site-packages/easybuild_framework-3.0.1-py2.7.egg/easybuild/main.py", line 295, in main
    eb_file = find_easybuild_easyconfig()
  File "/home/adam/.local/easybuild/software/EasyBuild/3.0.1/lib/python2.7/site-packages/easybuild_framework-3.0.1-py2.7.egg/easybuild/tools/github.py", line 1269, in find_easybuild_easyconfig
    dev_repo = download_repo(GITHUB_EASYCONFIGS_REPO, branch='develop', account=GITHUB_EB_MAIN)
  File "/home/adam/.local/easybuild/software/EasyBuild/3.0.1/lib/python2.7/site-packages/easybuild_framework-3.0.1-py2.7.egg/easybuild/tools/github.py", line 293, in download_repo
    latest_commit_sha = fetch_latest_commit_sha(repo, account, branch)
  File "/home/adam/.local/easybuild/software/EasyBuild/3.0.1/lib/python2.7/site-packages/easybuild_framework-3.0.1-py2.7.egg/easybuild/tools/github.py", line 255, in fetch_latest_commit_sha
    github_user=github_user, token=token, per_page=GITHUB_MAX_PER_PAGE)
  File "/home/adam/.local/easybuild/software/EasyBuild/3.0.1/lib/python2.7/site-packages/easybuild_framework-3.0.1-py2.7.egg/easybuild/tools/github.py", line 230, in github_api_get_request
    token = fetch_github_token(github_user)
  File "/home/adam/.local/easybuild/software/EasyBuild/3.0.1/lib/python2.7/site-packages/easybuild_framework-3.0.1-py2.7.egg/easybuild/tools/github.py", line 1194, in fetch_github_token
    return GithubToken(user).token
  File "/home/adam/.local/easybuild/software/EasyBuild/3.0.1/lib/python2.7/site-packages/easybuild_framework-3.0.1-py2.7.egg/easybuild/tools/github.py", line 1174, in __init__
    self.token = keyring.get_password(KEYRING_GITHUB_TOKEN, user)
  File "/usr/lib/python2.7/site-packages/keyring/core.py", line 42, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/usr/lib/python2.7/site-packages/keyring/backends/fail.py", line 18, in get_password
    raise RuntimeError("No recommended backend was available. Install the "
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
```

**Comment by verdurin** [comment]
See https://github.com/jaraco/keyring/issues/196

**Comment by verdurin** [comment]
Reported a Fedora bug at https://bugzilla.redhat.com/show_bug.cgi?id=1408952

**Comment by boegel** [comment]
@verdurin you can probably bypass this by not providing a GitHub username in your EasyBuild config, since it's not strictly required for `--install-latest-eb-release`...

**Comment by boegel** [comment]
@verdurin `fetch_github_token` should never yield a traceback, but simply fail to obtain a token instead (which is perfectly fine for `--install-latest-eb-release`); done in #2070, let's follow up there?
