### ISSUE TITLE
Problem using --from-pr with --job

### ISSUE THREAD

**Issue by verdurin** [hpcugent/easybuild-framework#2084]
Was just trying to build from a PR using the Job backend, and saw this error:
```
== temporary log file in case of crash /home/camp/huffmaa/tmp/eb-gJvMs1/eb-SNOCo9/easybuild-IoQcgx.log
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/camp/apps/eb/software/EasyBuild/3.0.2/lib/python2.7/site-packages/easybuild_framework-3.0.2-py2.7.egg/easybuild/main.py", line 443, in <module>
    main()
  File "/camp/apps/eb/software/EasyBuild/3.0.2/lib/python2.7/site-packages/easybuild_framework-3.0.2-py2.7.egg/easybuild/main.py", line 304, in main
    paths = det_easyconfig_paths(categorized_paths['easyconfigs'])
  File "/camp/apps/eb/software/EasyBuild/3.0.2/lib/python2.7/site-packages/easybuild_framework-3.0.2-py2.7.egg/easybuild/framework/easyconfig/tools.py", line 305, in det_easyconfig_paths
    pr_files = fetch_easyconfigs_from_pr(from_pr)
  File "/camp/apps/eb/software/EasyBuild/3.0.2/lib/python2.7/site-packages/easybuild_framework-3.0.2-py2.7.egg/easybuild/tools/github.py", line 341, in fetch_easyconfigs_from_pr
    status, pr_data = github_api_get_request(pr_url, github_user)
  File "/camp/apps/eb/software/EasyBuild/3.0.2/lib/python2.7/site-packages/easybuild_framework-3.0.2-py2.7.egg/easybuild/tools/github.py", line 232, in github_api_get_request
    url = request_f(RestClient(GITHUB_API_URL, username=github_user, token=token))
  File "/camp/apps/eb/software/EasyBuild/3.0.2/lib/python2.7/site-packages/vsc_base-2.5.5-py2.7.egg/vsc/utils/rest.py", line 284, in __init__
    self.client = Client(*args, **kwargs)
  File "/camp/apps/eb/software/EasyBuild/3.0.2/lib/python2.7/site-packages/vsc_base-2.5.5-py2.7.egg/vsc/utils/rest.py", line 99, in __init__
    raise TypeError("You need a password or an OAuth token to authenticate as " + username)
TypeError: You need a password or an OAuth token to authenticate as verdurin
```

even though I'd already opened the Python keyring for my GitHub token.

**Comment by verdurin** [comment]
It works fine without using the Job backend.

**Comment by boegel** [comment]
Does the problem also occur when you submit a job script that does `eb --from-pr` yourself?

**Comment by verdurin** [comment]
How would I supply a token to that job?

**Comment by boegel** [comment]
@verdurin the token is supposed to be available in your account (installed via `eb --install-github-token`, see http://easybuild.readthedocs.io/en/latest/Integration_with_GitHub.html#installing-a-github-token-install-github-token), but I guess it depends on how the `keyring` module is storing the token...

**Comment by verdurin** [comment]
It doesn't look the running manually with a job script invokes the `keyring` module either. I just see the same error.

**Comment by boegel** [comment]
well, it does use the `keyring` module, but your keyring may only be available in an interactive session

see for example https://pypi.python.org/pypi/keyring#using-keyring-on-headless-linux-systems
