### ISSUE TITLE
regtest doesn't catch broken urls when files are already available offline

### ISSUE THREAD

**Issue by migueldiascosta** [hpcugent/easybuild-framework#2087]
Regtest doesn't catch broken urls when files are already available offline (and they usually are when running regtests)

Verifying if the file can still be found at the source_url, without downloading if it is already available, would allow catching broken urls without making the regtest take much longer.

However, that verification could also fail merely because a server is temporarily inaccessible, so if this is implemented it should only issue a warning, I guess

**Comment by boegel** [comment]
We implement support for an option like `--verify-source-urls` which would do exactly this: verify whether files are still available at one of the listed `source_urls`...

Seems like this is actually quite trivial, since `urllib2.urlopen` will throw a traceback instantly when a non-existing URL is used:

```python
>>> import urllib2
# correct URL
>>> url_fd = urllib2.urlopen('https://github.com/google/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.gz')
>>> url_fd.msg
'OK'

# faulty URL
>>> url_fd = urllib2.urlopen('https://github.com/google/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.gzxx')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

**Comment by migueldiascosta** [comment]
indeed, I thought `urlopen` would immediately (re)download the file if the URL exists but no, only a subsequent `url_fd.read()` actually downloads...

do you think the `--verify-source-urls` option should be only for regtest or completely generic? If the latter, it could simply be added to `easyblock.obtain_file()`, e.g. something like

```python
# only download when it's not there yet                                                                                                                                                                                      
if os.path.exists(fullpath):
     self.log.info("Found file %s at %s, no need to download it." % (filename, filepath))
+     if build_option('verify_source_urls'):
+          # check anyway
+          self.log.debug("Verifying URL %s." % url)
+          try:
+               url_fd = urllib2.urlopen(url)
+          except HTTPError, err:
+               self.log.debug("Could not open URL %s: %s" % (url, err))
+               broken_urls.append(url)
+               continue
     return fullpath
```

changing `obtain_file()` would make this work also for extensions, patches, etc...

there could also be a `--force-download` option (not sure if there is a good case for that), that would simply be

```python
# only download when it's not there yet or if downloads are forced                                                                                                                                                                                      
if not build_option('force-download') and os.path.exists(fullpath):
```

**Comment by boegel** [comment]
@migueldiascosta I think this should be a stand-alone option, not tied to the regtest, so it can also be used in other circumstances

I'm not sure pushing this into `obtain_file` like you showed is the best approach though, since with the patch you showed `--verify-source-urls` would only be done for files that are already downloaded.

You want this to be entirely separate, i.e. to *only* check download URLs, and not do anything else (i.e. not build or even actually download).

**Comment by migueldiascosta** [comment]
@boegel ok, if it should _only_ verify source URLs, maybe it could imply `--stop=fetch` and run `urlopen` (and return before downloading) in all cases, not just the already downloaded ones

**Comment by migueldiascosta** [comment]
using this hack [1], found about 200 inaccessible source_urls [2]

[1] https://github.com/migueldiascosta/easybuild-framework/commit/57809aaaf88aef1d73440ec9fee7a1c1a80aa962
[2] https://gist.github.com/migueldiascosta/3330b976811131f6f6a97444999692bd
