### ISSUE TITLE
Test failure: KeyError: 'PYTHONPATH'

### ISSUE THREAD

**Issue by opoplawski** [hpcugent/easybuild-framework#2148]
Running tests with "/usr/bin/python2 setup.py test" I get lots of these errors:
```
Traceback (most recent call last):
  File "/export/home/orion/redhat/python-easybuild-framework/easybuild-framework-easybuild-framework-v3.1.1/test/framework/utilities.py", line 185, in setUp
    self.env_pythonpath = os.environ['PYTHONPATH']
  File "/usr/lib64/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'PYTHONPATH'
```
Looks like utilities.py needs to handle the case where PYTHONPATH is not set.

**Comment by boegel** [comment]
Should be fixed by the changes made in #2149, thanks for reporting this @opoplawski!
