### ISSUE TITLE
test_vsc_location (test.framework.general.GeneralTest) fails

### ISSUE THREAD

**Issue by opoplawski** [hpcugent/easybuild-framework#2154]
I'm working on building Fedora rpms for easybuild packages.  I'm getting the following test error:
```
ERROR [1.860s]: test_vsc_location (test.framework.general.GeneralTest)
Make sure location of imported vsc module is not the framework itself.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/export/home/orion/redhat/python-easybuild-framework/easybuild-framework-easybuild-framework-v3.1.1/test/framework/general.py", line 53, in test_vsc_location
    vsc_loc = os.path.dirname(os.path.dirname(os.path.abspath(vsc.__file__)))
AttributeError: 'module' object has no attribute '__file__'
```
The vsc-base package does not install a __init__.py file in site-packages/vsc, I believe because it is a namespace package, so it doesn't not have a __file__ attribute.

**Comment by boegel** [comment]
@opoplawski Hmm, this is new to me... I can probably come up with a patch that dances around this, for example by checking `vsc.utils.__file__` or `vsc.utils.fancylogger.__file__` instead, but I'd like to understand what is causing this exactly.

You may be right that this may be due to `vsc` being registered as a namespace package, but it may also indicate a mistake in the packaging of `vsc-base` and/or `vsc-install`.

Is that the only test failing in the whole suite?

Can we inspect the `vsc-base` and `vsc-install` packages that you are using as dependencies somewhere?

BTW, you should try and run the tests in Python 'optimised' mode, since the main `eb` command also uses `python -O`; one way is to define `$PYTHONOPTIMIZE` as `1`, see https://docs.python.org/2/using/cmdline.html#cmdoption-O .

**Comment by opoplawski** [comment]
One difference may be how you are installing the vsc packages when running the tests.  When you build the vsc packages locally, you get an __init__,py.  e.g.:
```
$ ls build/lib/vsc/
__init__.py  utils
$ PYTHONPATH=build/lib python -c 'import vsc;print vsc.__file__'
/export/home/orion/redhat/python-vsc-base/vsc-base-vsc-base-2.5.7/build/lib/vsc/__init__.pyc
```
But that doesn't get installed into site-packages.  Instead a .pth file is installed:
```
/usr/lib/python2.7/site-packages/vsc_base-2.5.7-py2.7-nspkg.pth
# ls /usr/lib/python2.7/site-packages/vsc
fancylogger.py  fancylogger.pyc  fancylogger.pyo  install  utils
```
In the Fedora build case, we install all of the dependencies via rpms instead of building them locally, and as a result there is no __file__ attribute for the namespace packages.

BTW - most of the test suite passes, there are only about 10 errors/failures.

**Comment by opoplawski** [comment]
One difference may be how you are installing the vsc packages when running the tests.  When you build the vsc packages locally, you get an __init__,py.  e.g.:
```
$ ls build/lib/vsc/
__init__.py  utils
$ PYTHONPATH=build/lib python -c 'import vsc;print vsc.__file__'
/export/home/orion/redhat/python-vsc-base/vsc-base-vsc-base-2.5.7/build/lib/vsc/__init__.pyc
```
But that doesn't get installed into site-packages.  Instead a .pth file is installed:
```
/usr/lib/python2.7/site-packages/vsc_base-2.5.7-py2.7-nspkg.pth
# ls /usr/lib/python2.7/site-packages/vsc
fancylogger.py  fancylogger.pyc  fancylogger.pyo  install  utils
```
In the Fedora build case, we install all of the dependencies via rpms instead of building them locally, and as a result there is no __file__ attribute for the namespace packages.

BTW - most of the test suite passes, there are only about 10 errors/failures.

**Comment by opoplawski** [comment]
#2159 does appear to fix this issue.  Other errors I see are:
```
RROR [2.742s]: test_check_style (test.framework.options.CommandLineOptionsTest)
Test --check-style.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/export/home/orion/redhat/python-easybuild-framework/easybuild-framework-easybuild-framework-v3.1.1/test/framework/options.py", line 3022, in test_check_style
    self.eb_main(args, raise_error=True)
  File "/export/home/orion/redhat/python-easybuild-framework/easybuild-framework-easybuild-framework-v3.1.1/test/framework/utilities.py", line 293, in eb_main
    raise myerr
AttributeError: 'Checker' object has no attribute 'total_lines'

======================================================================
ERROR [177.437s]: test_toy_rpath (test.framework.toy_build.ToyBuildTest)
Test toy build using --rpath.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/export/home/orion/redhat/python-easybuild-framework/easybuild-framework-easybuild-framework-v3.1.1/test/framework/toy_build.py", line 1251, in test_toy_rpath
    self.test_toy_build(extra_args=['--rpath', '--experimental'], raise_error=True)
  File "/export/home/orion/redhat/python-easybuild-framework/easybuild-framework-easybuild-framework-v3.1.1/test/framework/toy_build.py", line 145, in test_toy_build
    raise myerr
EasyBuildError: 'Build of /export/home/orion/redhat/python-easybuild-framework/easybuild-framework-easybuild-framework-v3.1.1/test/framework/easyconfigs/test_ecs/t/toy/toy-0.0.eb failed (err: \'build failed (first 300 chars): cmd " gcc toy.c -o toy " exited with exitcode 1 and output:\\nTraceback (most recent call last):\\n  File "/usr/lib64/python2.7/site.py", line 62, in <module>\\n    import os\\n  File "/usr/lib64/python2.7/os.py", line 398, in <module>\\n    import UserDict\\n  File "/usr/lib64/python2.7/UserDict.py", line 83, \')'

======================================================================
ERROR [2.179s]: test_fix_broken_easyconfig (test.framework.scripts.ScriptsTest)
Test fix_broken_easyconfigs.py script.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/export/home/orion/redhat/python-easybuild-framework/easybuild-framework-easybuild-framework-v3.1.1/test/framework/scripts.py", line 56, in setUp
    vsc_loc = os.path.dirname(os.path.dirname(os.path.abspath(vsc.__file__)))
AttributeError: 'module' object has no attribute '__file__'

======================================================================
ERROR [1.182s]: test_generate_software_list (test.framework.scripts.ScriptsTest)
Test for generate_software_list.py script.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/export/home/orion/redhat/python-easybuild-framework/easybuild-framework-easybuild-framework-v3.1.1/test/framework/scripts.py", line 56, in setUp
    vsc_loc = os.path.dirname(os.path.dirname(os.path.abspath(vsc.__file__)))
AttributeError: 'module' object has no attribute '__file__'

======================================================================
ERROR [1.150s]: test_gen_easyblocks (test.framework.docs.DocsTest)
Test gen_easyblocks_overview_rst function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/export/home/orion/redhat/python-easybuild-framework/easybuild-framework-easybuild-framework-v3.1.1/test/framework/docs.py", line 92, in test_gen_easyblocks
    self.assertTrue(re.search(regex, ebdoc), "Pattern %s found in %s" % (regex.pattern, ebdoc))
AssertionError: None is not true : Pattern :ref:`ConfigureMake` - :ref:`ConfigureMake` - :ref:`ConfigureMake` - :ref:`DummyExtension` - :ref:`DummyExtension` - :ref:`DummyExtension` - :ref:`Toolchain` - :ref:`Toolchain` - :ref:`Toolchain` - :ref:`Toy_Extension` - :ref:`Toy_Extension` - :ref:`Toy_Extension` - :ref:`bar` - :ref:`bar` - :ref:`bar` found in *(this page was generated automatically using* ``easybuild.tools.docs.gen_easyblocks_overview_rst()`` *)*

==============================
Overview of generic easyblocks
==============================

:ref:`ConfigureMake` - :ref:`DummyExtension` - :ref:`Toolchain` - :ref:`Toy_Extension` - :ref:`bar`

.. _ConfigureMake:

``ConfigureMake``
=================

(derives from EasyBlock)

Dummy support for building and installing applications with configure/make/make install.

Commonly used easyconfig parameters with ``ConfigureMake`` easyblock
--------------------------------------------------------------------

====================    ================================================================
easyconfig parameter    description                                                     
====================    ================================================================
configopts              Extra options passed to configure (default already has --prefix)
buildopts               Extra options passed to make step (default already has -j X)    
installopts             Extra options for installation                                  
====================    ================================================================


.. _DummyExtension:

``DummyExtension``
==================

(derives from ExtensionEasyBlock)

Support for building/installing dummy extensions.

Extra easyconfig parameters specific to ``DummyExtension`` easyblock
--------------------------------------------------------------------

====================    ==================================    =============
easyconfig parameter    description                           default value
====================    ==================================    =============
``options``             Dictionary with extension options.    ``{}``       
====================    ==================================    =============

.. _Toolchain:

``Toolchain``
=============

(derives from EasyBlock)

Dummy support for toolchains.

.. _Toy_Extension:

``Toy_Extension``
=================

(derives from ExtensionEasyBlock)

Support for building/installing toy.

Extra easyconfig parameters specific to ``Toy_Extension`` easyblock
-------------------------------------------------------------------

====================    ==================================    =============
easyconfig parameter    description                           default value
====================    ==================================    =============
``options``             Dictionary with extension options.    ``{}``       
====================    ==================================    =============

.. _bar:

``bar``
=======

(derives from EasyBlock)

Generic support for building/installing bar.

Extra easyconfig parameters specific to ``bar`` easyblock
---------------------------------------------------------

====================    ===================================================    =============
easyconfig parameter    description                                            default value
====================    ===================================================    =============
``bar_extra2``          second bar-specific easyconfig parameter               ``"BAR"``    
``bar_extra1``          first bar-specific easyconfig parameter (mandatory)    ``None``     
====================    ===================================================    =============


----------------------------------------------------------------------
```

**Comment by boegel** [comment]
Thanks for the confirmation on #2159 and reporting these issues @opoplawski!

W.r.t. the tests still failing:

* `test_check_style`: I'm not 100% sure what the problem is here (maybe an old version of the `pep8` module being used?), but I suspect that it may be fixed by #2160; in any case, `pycodestyle` should be preferred over `pep8` now, cfr. #2161

* `test_toy_rpath`: please try applying the patch below to this test why this is failing exactly:
```diff
diff --git a/test/framework/toy_build.py b/test/framework/toy_build.py
index 957c927..efef0b0 100644
--- a/test/framework/toy_build.py
+++ b/test/framework/toy_build.py
@@ -1248,7 +1248,7 @@ class ToyBuildTest(EnhancedTestCase):
 
     def test_toy_rpath(self):
         """Test toy build using --rpath."""
-        self.test_toy_build(extra_args=['--rpath', '--experimental'], raise_error=True)
+        self.test_toy_build(extra_args=['--rpath', '--experimental'], raise_error=True, verbose=True)
 
         # also test use of --rpath-filter
         self.test_toy_build(extra_args=['--rpath', '--rpath-filter=/test.*,/foo.*', '--experimental'], raise_error=True)
```
* `test_fix_broken_easyconfig`: fixed by #2164
* `test_generate_software_list`: fixed by #2164
* `gen_easyblocks_overview_rst`: fixed by #2164

**Comment by opoplawski** [comment]
Checking with latest develop branch fixes everything but test.framework.options.CommandLineOption and test.framework.toy_build.ToyBuildTestsTest.  Setting verbose didn't get me much by itself, so I also set first_n to 10000 and now get:
```
EasyBuildError: 'Build of /export/home/orion/redhat/python-easybuild-framework/easybuild-framework-ca7fc1effc80342f79cb3b973ca48eab9516a1ae/test/framework/easyconfigs/test_ecs/t/toy/toy-0.0.eb failed (err: \'build failed (first 10000 chars): cmd " gcc toy.c -o toy " exited with exitcode 1 and output:\\nTraceback (most recent call last):\\n  File "/usr/lib64/python2.7/site.py", line 62, in <module>\\n    import os\\n  File "/usr/lib64/python2.7/os.py", line 398, in <module>\\n    import UserDict\\n  File "/usr/lib64/python2.7/UserDict.py", line 83, in <module>\\n    import _abcoll\\n  File "/usr/lib64/python2.7/_abcoll.py", line 11, in <module>\\n    from abc import ABCMeta, abstractmethod\\n  File "/usr/lib64/python2.7/abc.py", line 8, in <module>\\n    from _weakrefset import WeakSet\\nImportError: No module named _weakrefset\\n\')'
```

**Comment by boegel** [comment]
@opoplawski 

* w.r.t. `AttributeError: 'Checker' object has no attribute 'total_lines'` that makes `test_check_style` fail: 

  * Are you still seeing that exact same `AttributeError`?
  * Which `pep8` version are you using?
  * Is also installing `pycodestyle` (which is basically the replacement of `pep8` an option, and does it help? (requires `develop` or the upcoming EasyBuild v3.1.2 to make a difference)

* reformatted traceback for `test_toy_rpath`

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site.py", line 62, in <module>
    import os
  File "/usr/lib64/python2.7/os.py", line 398, in <module>
    import UserDict
  File "/usr/lib64/python2.7/UserDict.py", line 83, in <module>
    import _abcoll
  File "/usr/lib64/python2.7/_abcoll.py", line 11, in <module>
    from abc import ABCMeta, abstractmethod
  File "/usr/lib64/python2.7/abc.py", line 8, in <module>
    from _weakrefset import WeakSet
ImportError: No module named _weakrefset
```

I don't think the latter is a problem in EasyBuild or the tests since it's triggered by a simple `import os`? This looks potentially relevant: https://bugs.launchpad.net/ubuntu/+source/python-virtualenv/+bug/662611 (well, it's not Fedora, but it's the exact same error) which points to http://bugs.python.org/issue2521.

Maybe you're using an old version of Python or virtualenv?

**Comment by opoplawski** [comment]
Same AttribueError.  pep8 is version 1.4.6.  I installed pycodestyle 2.0.0 and that cleared up that issue.

test_toy_rpath does appear to be virtualenv related, but I cannot reproduce with a simple virtualenv creation test case.

**Comment by boegel** [comment]
@opoplawski I couldn't find a related bug fix since `pep8` v1.4.6 in http://pep8.readthedocs.io/en/release-1.7.x/developer.html#changes, but I'm not sure if it's worth figuring this one out further since I haven't seen it with more recent versions of `pep8` either.

How do we proceed on the issue with `test_toy_rpath`? I don't think there's something we can do, looks like a bug in Python or virtualenv, right?

**Comment by opoplawski** [comment]
Can you get me the commands to run to reproduce the test_toy_rpath test?  With that I could probably track down the issue.  Thanks.

**Comment by boegel** [comment]
@opoplawski I'm not sure what you mean... Do you want to run the `test_toy_rpath` only?

Then use `python -O -m test.framework.suite test_toy_rpath`.

**Comment by boegel** [comment]
@opoplawski Any updates on this?
