### ISSUE TITLE
bug: eb/3.2.0 does not tolerate % character in description and the build crashes, fi. bzip2

### ISSUE THREAD

**Issue by fgeorgatos** [hpcugent/easybuild-framework#2216]
there were recent changes in the framework around generalization of handling the `description`, 
so they are possibly related (look carefully the stacktrace below). I switched `%` to `p.c.` as quick remedy.

fi. bzip2 build collapses as follows - across multiple toolchains:

```
[easybuild@localhost easybuild]$ time eb cairo-1.14.6-foss-2016a-GLib-2.48.0.eb -r
== temporary log file in case of crash /tmp/eb-qFJaCG/easybuild-cDuZ7f.log
== resolving dependencies ...
== processing EasyBuild easyconfig /scratch/DL/el7/0.1.0-83-g9259099/software/EasyBuild/3.2.0/lib/python2.7/site-packages/easybuild_easyconfigs-3.2.0-py2.7.egg/easybuild/easyconfigs/b/bzip2/bzip2-1.0.6-foss-2016a.eb
== building and installing bzip2/1.0.6-foss-2016a...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== postprocessing...
== sanity checking...
ERROR: Traceback (most recent call last):
  File "/scratch/DL/el7/0.1.0-83-g9259099/software/EasyBuild/3.2.0/lib/python2.7/site-packages/easybuild_framework-3.2.0-py2.7.egg/easybuild/main.py", line 117, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/scratch/DL/el7/0.1.0-83-g9259099/software/EasyBuild/3.2.0/lib/python2.7/site-packages/easybuild_framework-3.2.0-py2.7.egg/easybuild/framework/easyblock.py", line 2531, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/scratch/DL/el7/0.1.0-83-g9259099/software/EasyBuild/3.2.0/lib/python2.7/site-packages/easybuild_framework-3.2.0-py2.7.egg/easybuild/framework/easyblock.py", line 2447, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/scratch/DL/el7/0.1.0-83-g9259099/software/EasyBuild/3.2.0/lib/python2.7/site-packages/easybuild_framework-3.2.0-py2.7.egg/easybuild/framework/easyblock.py", line 2325, in run_step
    step_method(self)()
  File "/scratch/DL/el7/0.1.0-83-g9259099/software/EasyBuild/3.2.0/lib/python2.7/site-packages/easybuild_easyblocks-3.2.0-py2.7.egg/easybuild/easyblocks/b/bzip2.py", line 110, in sanity_check_step
    super(EB_bzip2, self).sanity_check_step(custom_paths=custom_paths)
  File "/scratch/DL/el7/0.1.0-83-g9259099/software/EasyBuild/3.2.0/lib/python2.7/site-packages/easybuild_framework-3.2.0-py2.7.egg/easybuild/framework/easyblock.py", line 1844, in sanity_check_step
    self._sanity_check_step(*args, **kwargs)
  File "/scratch/DL/el7/0.1.0-83-g9259099/software/EasyBuild/3.2.0/lib/python2.7/site-packages/easybuild_framework-3.2.0-py2.7.egg/easybuild/framework/easyblock.py", line 2041, in _sanity_check_step
    fake_mod_data = self.load_fake_module(purge=True)
  File "/scratch/DL/el7/0.1.0-83-g9259099/software/EasyBuild/3.2.0/lib/python2.7/site-packages/easybuild_framework-3.2.0-py2.7.egg/easybuild/framework/easyblock.py", line 1211, in load_fake_module
    fake_mod_path = self.make_module_step(fake=True)
  File "/scratch/DL/el7/0.1.0-83-g9259099/software/EasyBuild/3.2.0/lib/python2.7/site-packages/easybuild_framework-3.2.0-py2.7.egg/easybuild/framework/easyblock.py", line 2149, in make_module_step
    txt += self.make_module_description()
  File "/scratch/DL/el7/0.1.0-83-g9259099/software/EasyBuild/3.2.0/lib/python2.7/site-packages/easybuild_framework-3.2.0-py2.7.egg/easybuild/framework/easyblock.py", line 1000, in make_module_description
    return self.module_generator.get_description()
  File "/scratch/DL/el7/0.1.0-83-g9259099/software/EasyBuild/3.2.0/lib/python2.7/site-packages/easybuild_framework-3.2.0-py2.7.egg/easybuild/tools/module_generator.py", line 455, in get_description
    'installdir': self.app.installdir,
ValueError: unsupported format character 't' (0x74) at index 183


real    0m3.935s
user    0m5.649s
sys     0m0.899s
```

**Comment by boegel** [comment]
already fixed in `develop` via #2209, fix will be included in the upcoming EasyBuild v3.2.1 release
