### ISSUE TITLE
Failing test due to config.cfg

### ISSUE THREAD

**Issue by wpoely86** [hpcugent/easybuild-framework#833]
I've got 2 lines in my ```config.cfg```:
```
logtostdout=True
repository=GitRepository
```
This makes 11 tests fail. If I remove my config.cfg, all tests work.
All failing tests are related to ```test.framework.options*```. All of them (except the last one) are related to the first line in my ```config.cfg```. 

These fail:
```
======================================================================
FAIL: test_debug (test.framework.options.CommandLineOptionsTest)
Test enabling debug logging.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/framework/options.py", line 143, in test_debug
    self.assertTrue(res, "%s log messages are included when using %s: %s" % (log_msg_type, debug_arg, outtxt))
AssertionError: DEBUG log messages are included when using -d: 

======================================================================
FAIL: test_force (test.framework.options.CommandLineOptionsTest)
Test forcing installation even if the module is already available.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/framework/options.py", line 225, in test_force
    self.assertTrue(re.search(already_msg, outtxt), "Already installed message without --force, outtxt: %s" % outtxt)
AssertionError: Already installed message without --force, outtxt: 

======================================================================
FAIL: test_ignore_osdeps (test.framework.options.CommandLineOptionsTest)
Test ignoring of listed OS dependencies.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/framework/options.py", line 821, in test_ignore_osdeps
    self.assertTrue(regex.search(outtxt), "OS dependencies are checked, outtxt: %s" % outtxt)
AssertionError: OS dependencies are checked, outtxt: 

======================================================================
FAIL: test_info (test.framework.options.CommandLineOptionsTest)
Test enabling info logging.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/framework/options.py", line 165, in test_info
    self.assertTrue(res, "%s log messages are included when using %s (err: %s, out: %s)" % (log_msg_type, info_arg, myerr, outtxt))
AssertionError: INFO log messages are included when using --info (err: "EasyBuild crashed with an error (at easybuild/tools/build_log.py:155 in print_error): Unable to find an easyconfig for the given specifications: {'name': 'somethingrandom'}; to make EasyBuild try to generate a matching easyconfig, use the --try-X options ", out: )

======================================================================
FAIL: test_job (test.framework.options.CommandLineOptionsTest)
Test submitting build as a job.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/framework/options.py", line 356, in test_job
    self.assertTrue(re.search(job_msg, outtxt), assertmsg)
AssertionError: Info log message with job command template when using --job (job_msg: INFO.* Command template for jobs: .* && eb %\(spec\)s --debug.*
, outtxt: )

======================================================================
FAIL: test_no_args (test.framework.options.CommandLineOptionsTest)
Test using no arguments.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/framework/options.py", line 125, in test_no_args
    self.assertTrue(re.search(error_msg, outtxt), "Error message when eb is run without arguments")
AssertionError: Error message when eb is run without arguments

======================================================================
FAIL: test_no_such_software (test.framework.options.CommandLineOptionsTest)
Test using no arguments.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/framework/options.py", line 743, in test_no_such_software
    self.assertTrue(re.search(error_msg1, outtxt) or re.search(error_msg2, outtxt), msg)
AssertionError: Error message when eb can't find software with specified name (myerr: "EasyBuild crashed with an error (at easybuild/tools/build_log.py:155 in print_error): Unable to find an easyconfig for the given specifications: {'name': 'nosuchsoftware'}; to make EasyBuild try to generate a matching easyconfig, use the --try-X options ", outtxt: )

======================================================================
FAIL: test_quiet (test.framework.options.CommandLineOptionsTest)
Test enabling quiet logging (errors only).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/framework/options.py", line 190, in test_quiet
    self.assertTrue(res, "%s log messages are included when using %s (outtxt: %s)" % (log_msg_type, quiet_arg, outtxt))
AssertionError: ERROR log messages are included when using --quiet (outtxt: )

======================================================================
FAIL: test_skip (test.framework.options.CommandLineOptionsTest)
Test skipping installation of module (--skip, -k).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/framework/options.py", line 280, in test_skip
    self.assertTrue(found, "Module found message present with --skip, outtxt: %s" % outtxt)
AssertionError: Module found message present with --skip, outtxt: 

======================================================================
FAIL: test_tmpdir (test.framework.options.CommandLineOptionsTest)
Test setting temporary directory to use by EasyBuild.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/framework/options.py", line 780, in test_tmpdir
    self.assertTrue(found, "Log message for tmpdir found in outtxt: %s" % outtxt)
AssertionError: Log message for tmpdir found in outtxt: 

======================================================================
FAIL: test_default_config (test.framework.config.EasyBuildConfigTest)
Test default configuration.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/framework/config.py", line 112, in test_default_config
    self.assertEqual(config_options['repository'], 'FileRepository')
AssertionError: 'GitRepository' != 'FileRepository'

----------------------------------------------------------------------
```

**Comment by boegel** [comment]
fixed with #1167

see also http://easybuild.readthedocs.org/en/latest/Unit-tests.html#configuration (`$TEST_EASYBUILD...` needs to be used to configure EB under test)
