### ISSUE TITLE
Results of Framework Tests Suite on Cray Linux Environment

### ISSUE THREAD

**Issue by pforai** [hpcugent/easybuild-framework#951]
This is a verbatim copy from running the eb framework tests suite on Cray Linux Environment 5 UP2 (which is based on SUSE Linux SLES 11 SP2). 

Lmod was installed on this system as the default modules tool on that machine (EnvironmentModulesC version 3.2.6.7) is not able to successfully bootstrap an EB installation via the ```bootstrap_eb.py``` script. 

None of the cray supplied modules were loaded.

```
> python -m test.framework.suite 
WARNING: xmlrunner module not available, falling back to using unittest...

.F.........err: You need a password or an OAuth token to authenticate as easybuild_test
F/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/vsc/utils/generaloption.py:963: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  msg = err.message
................(skipping GitRepository test)
..(skipping SvnRepository test)
..........................................................E.EF................................./home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/test/framework/utilities.py:61: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  elif hasattr(err, 'message'):
/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/test/framework/utilities.py:62: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  msg = err.message
.Skipping test_read, no GitHub token available?
.Skipping test_read_api, no GitHub token available?
.Skipping test_walk, no GitHub token available?
.....................err: "EasyBuild crashed with an error (at easybuild/main.py:107 in build_and_install_software): Build of /tmp/tmptjLiU9/toy-broken.eb failed (err: 'build failed (first 300 chars): EasyBuild crashed with an error (at easybuild/framework/easyblock.py:1303 in checksum_step): Checksum verification for /home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/test/framework/sandbox/sources/toy/toy-0.0.tar.gz using cleary')"
F......E.............................E
======================================================================
ERROR: Test setting cmd via enviroment
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/test/framework/modulestool.py", line 109, in test_environment_command
    bmmt = BrokenMockModulesTool(mod_paths=[])
  File "/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/easybuild/tools/modules.py", line 171, in __init__
    self.check_module_function(allow_mismatch=build_option('allow_modules_tool_mismatch'))
  File "/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/easybuild/tools/modules.py", line 247, in check_module_function
    self.log.error(msg)
  File "/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/easybuild/tools/build_log.py", line 103, in error
    raise EasyBuildError(newMsg)
EasyBuildError: 'EasyBuild crashed with an error (at easybuild/tools/modules.py:247 in check_module_function): pattern \'.*echo\' (BrokenMockModulesTool) not found in defined \'module\' function.\nSpecify the correct modules tool to avoid weird problems due to this mismatch, see the --modules-tool and --avail-modules-tools command line options.\nOr alternatively, use --allow-modules-tool-mismatch to stop treating this as an error. Obtained definition of \'module\' function: module is a function\nmodule () \n{ \n    eval $($LMOD_CMD bash "$@");\n    [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)\n}\n'

======================================================================
ERROR: Test the mock module
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/test/framework/modulestool.py", line 86, in test_mock
    mmt = MockModulesTool(mod_paths=[])
  File "/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/easybuild/tools/modules.py", line 171, in __init__
    self.check_module_function(allow_mismatch=build_option('allow_modules_tool_mismatch'))
  File "/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/easybuild/tools/modules.py", line 247, in check_module_function
    self.log.error(msg)
  File "/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/easybuild/tools/build_log.py", line 103, in error
    raise EasyBuildError(newMsg)
EasyBuildError: 'EasyBuild crashed with an error (at easybuild/tools/modules.py:247 in check_module_function): pattern \'.*echo\' (MockModulesTool) not found in defined \'module\' function.\nSpecify the correct modules tool to avoid weird problems due to this mismatch, see the --modules-tool and --avail-modules-tools command line options.\nOr alternatively, use --allow-modules-tool-mismatch to stop treating this as an error. Obtained definition of \'module\' function: module is a function\nmodule () \n{ \n    eval $($LMOD_CMD bash "$@");\n    [ $? = 0 ] && eval $(${LMOD_SETTARG_CMD:-:} -s sh)\n}\n'

======================================================================
ERROR: Test toy build with custom umask settings.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/test/framework/toy_build.py", line 353, in test_toy_permissions
    curr_grp = grp.getgrgid(gid).gr_name
KeyError: 'getgrgid(): gid not found: 62029'

======================================================================
ERROR: Test for generate_software_list.py script.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/test/framework/scripts.py", line 49, in test_generate_software_list
    pythonpath = os.environ['PYTHONPATH']
  File "/usr/lib64/python2.6/UserDict.py", line 22, in __getitem__
    raise KeyError(key)
KeyError: 'PYTHONPATH'

======================================================================
FAIL: Test allowing mismatch of modules tool with 'module' function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/test/framework/options.py", line 935, in test_allow_modules_tool_mismatch
    self.assertTrue(found_regex.search(outtxt), "Found debug message w.r.t. module function: %s" % outtxt[-600:])
AssertionError: Found debug message w.r.t. module function: dstyle key install_path usage found, replacing with newkey installpath
== 2014-06-19 10:33:44,006 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle key repository_path usage found, replacing with newkey repositorypath
== 2014-06-19 10:33:44,006 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle key log_dir usage found, replacing with newkey tmp_logdir
== 2014-06-19 10:33:44,006 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle key log_format usage found, replacing with newkey logfile_format


======================================================================
FAIL: Test fetching easyconfigs from a PR.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/test/framework/options.py", line 626, in test_from_pr
    self.assertTrue(regex.search(outtxt), "Found pattern %s in %s" % (regex.pattern, outtxt))
AssertionError: Found pattern ^ \* \[.\] .*/icc-2013_sp1.2.144.eb \(module: icc/2013_sp1.2.144\)$ in == 2014-06-19 10:34:23,042 runpy.config INFO Temporary directory used in this EasyBuild run: /tmp/easybuild-i7Meex
== 2014-06-19 10:34:23,042 runpy.environment INFO Environment variable TMPDIR set to /tmp/easybuild-i7Meex
== 2014-06-19 10:34:23,043 runpy.environment INFO Environment variable TEMP set to /tmp/easybuild-i7Meex
== 2014-06-19 10:34:23,043 runpy.environment INFO Environment variable TMP set to /tmp/easybuild-i7Meex
== 2014-06-19 10:34:23,044 runpy.run WARNING Can't find file /etc/profile.d/modules.sh
== 2014-06-19 10:34:23,056 runpy INFO This is EasyBuild 1.13.0 (framework: 1.13.0, easyblocks: 1.13.0) on host swan.
== 2014-06-19 10:34:23,058 runpy INFO Command line: --buildpath=/tmp/tmpE_bJ6L --dry-run --from-pr=726 --github-user=easybuild_test --installpath=/tmp/tmp4sD9RI --modules-tool=Lmod --robot=/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/test/framework/easyconfigs --sourcepath=/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/test/framework/sandbox/sources --unittest-file=/tmp/eb-test-dnRdYO.log
== 2014-06-19 10:34:23,060 runpy INFO Using /tmp/easybuild-i7Meex as temporary directory
== 2014-06-19 10:34:23,061 runpy INFO Using robot path(s): /home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/test/framework/easyconfigs
== 2014-06-19 10:34:23,063 runpy.run WARNING Can't find file /etc/profile.d/modules.sh
== 2014-06-19 10:34:23,070 runpy INFO Extended list of robot paths with paths for installed easyconfigs: ['/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/test/framework/easyconfigs', '/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_easyconfigs-1.13.0.0-py2.6.egg/easybuild/easyconfigs']
== 2014-06-19 10:34:23,073 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle init with modifications to support oldstyle options
== 2014-06-19 10:34:23,073 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle_init filename /ufs/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/easybuild/easybuild_config.py kwargs {}
== 2014-06-19 10:34:23,074 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle_read_configuration filename /ufs/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/easybuild/easybuild_config.py
== 2014-06-19 10:34:23,078 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: Adapt code to use read_environment from easybuild.tools.utilities and do not use oldstyle environment variables
== 2014-06-19 10:34:23,079 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle key build_path usage found, replacing with newkey buildpath
== 2014-06-19 10:34:23,079 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle key module_classes usage found, replacing with newkey moduleclasses
== 2014-06-19 10:34:23,080 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle key source_path usage found, replacing with newkey sourcepath
== 2014-06-19 10:34:23,081 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle key install_path usage found, replacing with newkey installpath
== 2014-06-19 10:34:23,082 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle key repository_path usage found, replacing with newkey repositorypath
== 2014-06-19 10:34:23,082 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle key log_dir usage found, replacing with newkey tmp_logdir
== 2014-06-19 10:34:23,083 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle key log_format usage found, replacing with newkey logfile_format
== 2014-06-19 10:34:23,087 runpy.Lmod INFO Prepended list of module paths with path used by EasyBuild: /tmp/tmp4sD9RI/modules/all
== 2014-06-19 10:34:23,088 runpy.Lmod INFO $MODULEPATH set based on list of module paths: /tmp/tmp4sD9RI/modules/all:/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/test/framework/modules
== 2014-06-19 10:34:23,088 runpy.filetools INFO Command /home/users/p02029/lmod/lmod/lmod/libexec/lmod found at /home/users/p02029/lmod/lmod/lmod/libexec/lmod
== 2014-06-19 10:34:23,089 runpy.Lmod INFO Full path for module command is /home/users/p02029/lmod/lmod/lmod/libexec/lmod, so using it
== 2014-06-19 10:34:23,090 runpy.run WARNING Can't find file /etc/profile.d/modules.sh
== 2014-06-19 10:34:23,262 runpy.Lmod INFO Found version 5.6.2
== 2014-06-19 10:34:23,332 runpy.Lmod WARNING Ignoring non-existing module path in $MODULEPATH: /tmp/tmp4sD9RI/modules/all
== 2014-06-19 10:34:23,394 runpy.github WARNING Failed to obtain GitHub token from keyring, required Python module https://pypi.python.org/pypi/keyring is not available.
== 2014-06-19 10:34:23,395 runpy.filetools INFO Creating directory /tmp/easybuild-i7Meex/files_pr726 (parents: True, set_gid: False, sticky: False)
== 2014-06-19 10:34:23,404 runpy.run WARNING Can't find file /etc/profile.d/modules.sh
== 2014-06-19 10:34:23,412 runpy.easyconfig.tools WARNING eb not found (which: no eb in (/home/users/p02029/lmod/lmod/5.6.2/libexec:/home/users/p02029/lmod/lmod/5.6.2/libexec:/home/users/p02029/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin:/usr/games:/usr/lib64/jvm/jre/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:.:/usr/lib/qt3/bin)
), failed to determine installation prefix
== 2014-06-19 10:34:23,417 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: The user easybuild dir has moved from /home/users/p02029/.easybuild to /home/users/p02029/.config/easybuild.
== 2014-06-19 10:34:23,418 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: get_default_oldstyle_configfile oldstyle configfile /ufs/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/easybuild/easybuild_config.py used
== 2014-06-19 10:34:23,418 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: get_default_oldstyle_configfile_defaults
== 2014-06-19 10:34:23,437 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle init with modifications to support oldstyle options
== 2014-06-19 10:34:23,438 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle_init filename /ufs/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/easybuild/easybuild_config.py kwargs {}
== 2014-06-19 10:34:23,439 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle_read_configuration filename /ufs/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/easybuild/easybuild_config.py
== 2014-06-19 10:34:23,442 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: Adapt code to use read_environment from easybuild.tools.utilities and do not use oldstyle environment variables
== 2014-06-19 10:34:23,443 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle key build_path usage found, replacing with newkey buildpath
== 2014-06-19 10:34:23,444 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle key module_classes usage found, replacing with newkey moduleclasses
== 2014-06-19 10:34:23,445 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle key source_path usage found, replacing with newkey sourcepath
== 2014-06-19 10:34:23,445 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle key install_path usage found, replacing with newkey installpath
== 2014-06-19 10:34:23,446 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle key repository_path usage found, replacing with newkey repositorypath
== 2014-06-19 10:34:23,447 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle key log_dir usage found, replacing with newkey tmp_logdir
== 2014-06-19 10:34:23,447 runpy.config WARNING Deprecated functionality, will no longer work in v2.0: oldstyle key log_format usage found, replacing with newkey logfile_format


======================================================================
FAIL: Test whether mismatch detection between modules tool and 'module' function works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/test/framework/modulestool.py", line 151, in test_module_mismatch
    self.assertTrue(warn_regex.search(logtxt))
AssertionError

======================================================================
FAIL: Test deliberately broken toy build.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/test/framework/toy_build.py", line 187, in test_toy_broken
    verify=False, fails=True, verbose=True, raise_error=True)
  File "/home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/test/framework/utilities.py", line 71, in assertErrorRegex
    self.assertTrue(re.search(regex, msg), "Pattern '%s' is found in '%s'" % (regex, msg))
AssertionError: Pattern 'Checksum verification .* failed' is found in 'EasyBuild crashed with an error (at easybuild/main.py:107 in build_and_install_software): Build of /tmp/tmptjLiU9/toy-broken.eb failed (err: 'build failed (first 300 chars): EasyBuild crashed with an error (at easybuild/framework/easyblock.py:1303 in checksum_step): Checksum verification for /home/users/p02029/.local/software/EasyBuild/1.13.0/lib64/python2.6/site-packages/easybuild_framework-1.13.0-py2.6.egg/test/framework/sandbox/sources/toy/toy-0.0.tar.gz using cleary')'

----------------------------------------------------------------------
Ran 187 tests in 812.066s

FAILED (failures=4, errors=4)
ERROR: Not all tests were successful.
Log available at /tmp/easybuild-tests-yKFUAM.log 
```

**Comment by pforai** [comment]
Closed due to relevancy and old age :)
